# ワークフロー名
name: tweet_current_time
on:
  # schedule:
    # 定期実行する時間（グリニッジ標準時）
    # - cron: '0 22 * * *'
  workflow_dispatch:
# ワークフローの実行は、順次または並行して実行される1つまたは複数のジョブで構成されます。
jobs:
  # ジョブ1: tweet
  tweet:
    # Ubuntuの最新版を指定
    runs-on: ubuntu-latest
    # このジョブのGitHub環境を指定
    environment: twitter
    # ステップは、ジョブの一部として実行されるタスクのシーケンスを表す
    steps:
      # GITHUB_WORKSPACE以下にリポジトリをチェックアウト
      - name: checkout repository
        uses: actions/checkout@v3
      # Python インストール
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # 必要なパッケージインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy
      # Tweet送信
      - name: Run Python
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          ls -la
          python $GITHUB_WORKSPACE/main.py
